steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/turgcp/tur-repository/tur:v1.0', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/turgcp/tur-repository/tur:v1.0']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - '-c'
      - |
        kubectl set image deployment/tur-backend express-container=us-central1-docker.pkg.dev/turgcp/tur-repository/tur:v1.0 --record

options:
  logging: CLOUD_LOGGING_ONLY

serviceAccount: projects/turgcp-id/serviceAccounts/turgcp@appspot.gserviceaccount.com